### ISSUE TITLE
Add block by block placement option

### ISSUE THREAD

**Issue by MicleBrick** [MicleBrick/ExplosionRegen#1]
Likely implemented by assigning a random delay to each block on explode for additional regeneration delay, configurable

**Comment by olekristian** [comment]
+1

**Comment by BornToDoStuff** [comment]
+1

this is vital to avoid suffocating players and mobs when the blocks regen.

**Comment by rsammelson** [comment]
+1

**Comment by MicleBrick** [comment]
I will look into implementing this after finals

**Comment by rsammelson** [comment]
What I added is not quite block by block, but it is based on distance, placing layers of blocks at a time.

**Comment by MicleBrick** [comment]
Thanks to @rsammelson for his PR which essentially makes it place it cubic layer by later, kind of like block by block placement but the pieces fall back in place in style, Buzz Light-year would be proud.

I will try to make this available on Spigot and GitHub releases soon, got an exam and a partial project submission due tomorrow and a lot of homework due short after that, plus some work to catch up on, so it might be sometime this weekend.

**Comment by BornToDoStuff** [comment]
Wondering what the status of this one is because I am excited for it. 
No rush, I know you have school and that comes first, but I am eagerly waiting for when you get time to push out this update.

**Comment by MicleBrick** [comment]
tbh looking like it won't be till summer, sorry

**Comment by rsammelson** [comment]
@MicleBrick what do you need to do in order to release this?

**Comment by MicleBrick** [comment]
just need to test it and release it, takes time tho. There's only a few
weeks left anyway, shouldn't be too much longer

**Comment by BornToDoStuff** [comment]
I am available to help you bug test this whenever you are able to get this feature pushed out! Once this and issue #11 are resolved I will be installing this plugin almost immediately on my server.

**Comment by MicleBrick** [comment]
I'm actually planning on doing it later today. thanks for the offer but I should be able to test it myself.

**Comment by MicleBrick** [comment]
actually forgot to do it cause i got caught up with other stuff lol, sorry. i'll do it right after work today

**Comment by BornToDoStuff** [comment]
This works, and is a good start. However the main reason to do this is to keep players and mobs from getting trapped inside the explosion regen zone and dieing of suffocation. Right now it looks cool, but the blocks seem to regen from closest to the point of explosion to the farthest away from the explosion which almost always ends with anything inside a creeper, ghast, or wither "pit" suffocating because the "ceiling" regenerates before the "floor".
To make this a more useful feature the blocks need to regenerate in a specific order. From the inside out. Farthest from impact to closest to impact in other words.
Additionally, the timing set in the config is either unclear or incorrect as when I time it the blocks begin to regen at approximately 24 seconds and finish at around 30 seconds when regen delay is set to 1.0 (meaning there should be an entire minute before they even start regenerating, and they finish in half of that). If this is intended then the config should be more clear but I believe this is an error.

**Comment by MicleBrick** [comment]
Pls open new issues for those suggestions/bugs
